name: Build the Ansible docsite

on:
  workflow_call:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  build-docsite:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Set up nox
        uses: wntrblm/nox@2023.04.22
        with:
          python-versions: "3.11"
      - name: Build the docsite with nox
        run: nox -e build
      - name: Create a downloadable archive of docs build
        uses: actions/upload-artifact@v3
        with:
          name: docsite-html-assets
          path: output/**
          retention-days: 7
